apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackpiro
  labels:
    app: jackpiro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackpiro
  template:
    metadata:
      labels:
        app: jackpiro
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: jackpiro
        image: murremway/jackpiro
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80