name: Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your desired region

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name remzy --region us-east-1
          kubectl config use-context remzy

      - name: Deploy to Kubernetes
        run: kubectl apply -f deploy.yml

      - name: Deploy Service to Cluster 
        run: Kubectl apply -f service.yml
      
      - name: Deploy Grafana Dashboard
        run: kubectl create -f manifests/setup

      - name: Deploy manifests/setup
        run: kubectl create -f manifests/
